Added a simple compilation test and linux CI (and fix linux build)
GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator pull request #446
Opened 2024-08-28 23:31 UTC by Mrkol

Trivial compilation test is required because the sample is windows-specific. Linux CI is needed because pull requests must stop breaking linux builds. The tiny `m_Handle(VMA_NULL)` -> `m_Handle()` fix is needed to fix linux CI.

As promised @adam-sawicki-a

2024-09-02 11:42 UTC, adam-sawicki-a requested changes

2024-09-02 11:42 UTC, adam-sawicki-a commented on include/vk_mem_alloc.h
> +#endif // VMA_EXTERNAL_MEMORY_WIN32
It seems that you change many lines that are unrelated to your change due to using some automated formatting tools. Changes like this make it difficult to analyze the history of a file later (like "blame" function).

2024-09-02 11:42 UTC, adam-sawicki-a commented on compilation_test/vma_impl.cpp
Would it be possible to reuse VulkanSample app for testing compilation on Linux instead of creating a new project? VulkanSample.cpp and VmaUsage.* files already have appropriate `#ifdef`-s and even some Clang-specific `#pragma` directives.

2025-03-12 02:36 UTC, IAmNotHanni commented on compilation_test/vma_impl.cpp
Does this mean we have to port VulkanSample app to Linux? I would be happy to help.

2025-03-12 02:38 UTC, IAmNotHanni commented
Does this pull request mean you want to move away from appveyor and use just GitHub actions instead? I could help with that. In my opinion, it would be nice to have a CI for Windows and Linux and both Debug and Release.

2025-03-12 10:38 UTC, adam-sawicki-a commented
@IAmNotHanni Help is very welcome. It would be good to have CI builds set up for both Windows and Linux using some free online service. We had AppVeyor for Windows and TravisCI for Linux. Unfortunately, TravisCI stopped working >2 years ago. AppVeyor is still testing Windows.

It is enough to test if the library compiles successfully (both public interface and the code under `VMA_IMPLEMENTATION`).

Running some actual tests in CI could be considered in the future, but that would require access to some Vulkan implementation on the server (a GPU or software emulation) and likely major changes in the sample app and testing code, which I would prefer to avoid. The problem is I use Windows at work and I don't have a local Linux development environment to be able to test and fix things.

2025-03-13 02:16 UTC, IAmNotHanni commented on include/vk_mem_alloc.h
> +#endif // VMA_EXTERNAL_MEMORY_WIN32
@Mrkol Let me know if you need help doing this :)

2025-04-02 14:13 UTC, adam-sawicki-a commented
The proposed code fails with error:

>Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v2`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down

2025-04-02 22:56 UTC, IAmNotHanni commented
> The proposed code fails with error:
> 
> > Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v2`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down

Use `actions/checkout@v4` like in here: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/.github/workflows/build.yml

2025-04-03 08:04 UTC, adam-sawicki-a commented
File ".github/workflows/linux.yaml" added by this change uses "actions/checkout@v4". I think it's the external repository "humbletim/install-vulkan-sdk@v1.1.1" referenced by this change that triggers this error. I think we should just download and install Vulkan SDK (or just its headers) without referencing such external repository.

2025-04-03 09:02 UTC, IAmNotHanni commented
> File ".github/workflows/linux.yaml" added by this change uses "actions/checkout@v4". I think it's the external repository "humbletim/install-vulkan-sdk@v1.1.1" referenced by this change that triggers this error. I think we should just download and install Vulkan SDK (or just its headers) without referencing such external repository.

Yes, it should be downloaded directly from Khronos like this for example:

```
- name: Install Vulkan SDK
  shell: bash
  run: |
    curl -LS -o vulkansdk.tar.xz https://sdk.lunarg.com/sdk/download/${{ env.VMA_VULKAN_VERSION }}/linux/vulkansdk-linux-x86_64-${{ env.VMA_VULKAN_VERSION }}.tar.xz
    echo "${{ env.VMA_VULKAN_SDK_CHECKSUM_LINUX }} vulkansdk.tar.xz" | sha256sum --check
    mkdir -p ${{ env.VMA_VULKAN_SDK_PATH }}
    tar xf vulkansdk.tar.xz -C "${{ env.VMA_VULKAN_SDK_PATH }}"
    rm -rf vulkansdk.tar.xz
```

2025-04-03 15:51 UTC, IAmNotHanni commented
@adam-sawicki-a Looking at the recent changes you pushed to main branch, one thing which points out to me is that clang and gcc seem to display no warnings at all in the CI build. In my experience, gcc and clang are much more detailed with warnings and they usually catch things which MSVC does not report by default. Maybe flags like `-Wall` and `-Wextra` are required to display any warnings?

2025-04-03 15:53 UTC, adam-sawicki-a commented
Yes, this sounds like a good idea as long as those warnings don't fail the build. Can you please propose such change?

2025-04-03 15:53 UTC, IAmNotHanni commented
Also, don't forget that in VmaSample code, there are a lot of `#indef _WIN32`, so on Linux, no code is realyl compiled from the tests. I guess the library itself is compiled though? I'm still working on https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/466 so we can have unit tests in the console on Linux :)

2025-04-03 15:53 UTC, closed without merging

2025-04-03 15:53 UTC, adam-sawicki-a commented
I added Linux CI build as #477, based on this ticket. Thank you very much for your help with it.

2025-04-03 15:53 UTC, IAmNotHanni commented
> Yes, this sounds like a good idea as long as those warnings don't fail the build. Can you please propose such change?

Yes, let me see..